server {
    listen 80;
    server_name aputri-a.42.fr;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name aputri-a.42.fr;

    root /var/www/html;
    index index.php index.html index.htm;

    ssl_certificate     /etc/ssl/private/nginx.crt;
    ssl_certificate_key /etc/ssl/private/nginx.key;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        include fastcgi.conf;
        fastcgi_pass wordpress:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location /static_site/ {
        proxy_pass http://static_site/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /adminer/ {
        proxy_pass http://adminer/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /portainer/ {
        proxy_pass http://portainer:9000/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

}
